routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.dashboard', [
    	'title' => "Dasboard"
    ]);
});
Route::resource('/nutrisi/lahan', 'Admin\LahanController');
Route::resource('/nutrisi/sensor', 'Admin\SensorController');
Route::resource('/nutrisi/hasil-akhir', 'Admin\HasilAkhirController');

app/Lahan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Lahan extends Model
{
    //
    protected $table = "lahan";
    protected $primarykey = "id";
    
    protected $fillable = [
    	'luas_lahan',
    	'keterangan'
    ];
}

app/Http/Controllers/Admin/LahanController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;
use App\Lahan;
use App\HasilAkhir;

class LahanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['title'] = 'Data Lahan';
        $data['data'] = Lahan::all();
        return view('admin.lahan.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['title'] = "Data Lahan Baru";
        return view('admin.lahan.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->session()->has('lahan_id')) {
            $request->session()->forget('lahan_id');
        }
        
        try {
            $validate = Validator::make($request->all(),[
                'luas_lahan' => 'required|min:3|numeric',
                'keterangan' => 'required|min:3'
            ]);

            if ($validate->fails()) {
                 return redirect(route('lahan.create'))->withErrors($validate, 'lahan')
                        ->withInput();
            }

            $createLahan = Lahan::create($request->all());
            if ($createLahan) {
                $getLahan = Lahan::orderBy('id','desc')->first();
                $request->session()->put('lahan_id',$getLahan->id);
                
                return redirect(route('sensor.create'));
            }

        } catch (Exception $e) {
            $e->getMessage();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/lahan/create.blade.php
@extends('layouts.dashboard')

@section('styles')
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.css" />
@endsection

@section('content')

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      {!! Form::open([
          'url' => route('lahan.store'),
          'method' => 'POST',
          'enctype' => 'multipart/form-data'
          ])
      !!}
      {!! csrf_field() !!}
        @include('admin.lahan.form')
      {!! Form::close() !!}
    </div>
  </div>

@endsection
@section('scripts')
  <script src="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.min.js"></script>
  <script type="text/javascript">
    jQuery(document).ready(function() {
      jQuery('#description').summernote({
        height: 300,
      });
    });
  </script>
@endsection

resources/views/admin/lahan/edit.blade.php
@extends('layouts.dashboard')

@section('styles')
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.css" />
  {{-- <link rel="stylesheet" type="text/css" href="{{ asset('assets/admin-template/plugins/datatables/DataTables-1.10.18/css/dataTables.bootstrap.min.css') }}"> --}}

@endsection

@section('content')

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      {!! Form::model($data, ['url' => route('categories.update',$data->id), 'method' => 'PUT','enctype'=>'multipart/form-data']) !!}
      {!! csrf_field() !!}
        @include('admin.categories.form')
      {!! Form::close() !!}
    </div>
  </div>

@endsection

@section('scripts')
  <script src="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.min.js"></script>
  <script type="text/javascript">
    jQuery(document).ready(function() {
      jQuery('#description').summernote({
        height: 300,
      });
    });
  </script>
@endsection

resources/views/admin/lahan/form.blade.php
<div class="row">

	<div class="col-md-12">
		<div class="form-group">
			<label class="col-md-2 control-label" for="luas_lahan">Luas Lahan</label>
			<div class="col-md-10">
				{{ Form::text('luas_lahan', null, ['class' => 'form-control','id' => 'luas_Lahan','placeholder' => 'Luas Lahan']) }}
			</div>
		</div>
		<div style="padding-bottom:50px;"></div>
	</div>

	<div class="col-md-12">
		<div class="form-group">
			<label class="col-md-2 control-label" for="keterangan">Nama Pemilik</label>
			<div class="col-md-10">
				{{ Form::text('keterangan', null, ['class' => 'form-control','id' => 'nama_pemilik','placeholder' => 'Nama Pemilik']) }}
			</div>
		</div>
		<div style="padding-bottom:50px;"></div>
	</div>
	
	<div class="col-md-12">
    <button type="submit" class="btn btn-primary btn-sm pull-right">
      <i class="fa fa-save"></i> Simpan
    </button>
    <div style="padding-bottom:20px;"></div>
	</div>

</div>

resources/views/admin/lahan/index.blade.php
@extends('layouts.dashboard')
@section('content')

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <p>
            <a href="{{ route('lahan.create') }}" class="btn btn-primary btn-sm">
                <i class="fa fa-plus">Lahan Baru</i>
            </a>    
        </p>
        
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12">

      <table class="table lahan_datatable">

        <thead>
          <tr>
            <th class="text-center">No</th>
            <th class="text-center">Luas Lahan</th>
            <th class="text-center">Keterangan</th>            
            <th class="text-center">Action</th>
          </tr>
        </thead>

        <tbody>
          
          @php
            $no= 1;
          @endphp


          @foreach($data as $row)
          <tr class="text-center">
            <td class="text-center">{{$no}}</td>
            <td class="text-center">{{$row->luas_lahan}}</td>
            <td class="text-center">{{$row->keterangan}}</td>
            <td class="text-center">
              <a href="{{ route('lahan.edit',$row->id) }}" class="btn btn-primary btn-sm">
                <i class="fa fa-edit"></i>
              </a>
                
              {!! Form::open(array(
                  'route'=>array('lahan.destroy',$row->id),
                  'method'=>'DELETE',
                  '_token'=> csrf_token(),
                  'style' => 'display:inline')) !!}
    
                  <button class="btn btn-danger btn-sm" type="submit"><i class="fa fa-trash"></i></button>
              {!!Form::close()!!}
                
            </td>
          </tr>

          @php
            $no++;
          @endphp

          @endforeach

        </tbody>  
      </table>

    </div>
  </div>

@endsection

@section('scripts') 

  <script type="text/javascript">
    jQuery('.lahan_datatable').DataTable();
  </script>

@endsection