routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.dashboard', [
    	'title' => "Dasboard"
    ]);
});
Route::resource('/nutrisi/lahan', 'Admin\LahanController');
Route::resource('/nutrisi/sensor', 'Admin\SensorController');
Route::resource('/nutrisi/hasil-akhir', 'Admin\HasilAkhirController');

app/HasilAkhir.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class HasilAkhir extends Model
{
    protected $table = "hasil_akhir";
    protected $primarykey = "id";
    protected $fillable = [
    	'lahan_id',
    	'sensor_keasaman',
    	'sensor_kelembapan',
    	'sensor_warna',
    	'takaran_keasaman',
    	'takaran_kelembapan',
    	'takaran_warna',
    ];

    public function lahan()
    {
    	return $this->belongsTo(Lahan::class);
    }
}

app/Http/Controllers/Admin/HasilAkhirController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\HasilAkhir;
use App\lahan;
use App\ReferensiAir;
use App\ReferensiKapur;
use App\ReferensiPupuk;

class HasilAkhirController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['title'] = "Data Hasil Akhir";
        $data['data'] = HasilAkhir::with('lahan')->get();
        return view('admin.hasil-akhir.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.hasil-akhir.create',['title' => "Lanjutkan proses Pencarian takaran nutrisi"]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $getLahanId = 2;
        $getLahanId = $request->session()->get('lahan_id');
        
        if ($getLahanId) {
            $getSensor = HasilAkhir::select([
                'hasil_akhir.sensor_keasaman as keasaman',
                'hasil_akhir.sensor_kelembapan as kelembapan',
                'hasil_akhir.sensor_warna as warna',
                'hasil_akhir.lahan_id as lahan_id',
            ])->join('lahan','lahan.id','=','lahan_id')
            ->where('lahan_id',$getLahanId)
            ->first();

            //Pencarian Takaran Air
            if ($getSensor['kelembapan'] && $getSensor['warna']) {
                $getTakaranAir = ReferensiAir::Select([
                    'referensi_air.kelembapan as kelembapan',
                    'referensi_air.takaran_air as takaran_air'
                ])->where('kelembapan',$getSensor['kelembapan'])->first();

                if ($getTakaranAir['takaran_air'] != 0) {
                    if ($getSensor['warna'] == "KELABU") {
                        $takaranAir = [
                            'jumlah_air' => $getTakaranAir['takaran_air'],
                            'keterangan' => "Disiram 2 hari Sekali"
                        ]; 
                    }
                    if ($getSensor['warna'] == "MERAH") {
                        $takaranAir = [
                            'jumlah_air' => $getTakaranAir['takaran_air'] + 100,
                            'keterangan' => "Disiram 2 hari Sekali"
                        ];
                    }
                    if ($getSensor['warna'] == "KUNING") {
                        $takaranAir = [
                            'jumlah_air' => $getTakaranAir['takaran_air'] + 200,
                            'keterangan' => "Disiram 2 hari Sekali"
                        ];
                    }
                }elseif ($getTakaranAir['takaran_air'] == 0){
                    $takaranAir = [
                        'jumlah_air' => $getTakaranAir['takaran_air'],
                        'keterangan' => "Bedengan sedalam 10-20 cm"
                    ];
                }
            }

            //Pencarian Takaran Kapur
            if ($getSensor['keasaman'] && $getSensor['warna']) {
                if ($getSensor['keasaman'] <= 6.5 && $getSensor['keasaman'] > 0) {
                    $selisihPh = 6.5 - $getSensor['keasaman'];
                    $keterangan = "KAPUR";
                }elseif ($getSensor['keasaman'] > 6.5 && $getSensor['keasaman'] <= 14) {
                    $selisihPh = $getSensor['keasaman'] - 6.5;
                    $keterangan = "BELERANG";
                }
                $selisihPh = number_format((float)$selisihPh, 2, '.', '');
                $getReferensiKapur = ReferensiKapur::where('selisih_ph',$selisihPh)->first();
                $getLahan = Lahan::where('id',$getLahanId)->first();
                // return $getLahan;
                if ($getReferensiKapur) {
                    if ($getSensor['warna']="KELABU") {
                        $takaranPh = ($getLahan->luas_lahan * $getReferensiKapur->takaran)/10000;
                    }
                    if ($getSensor['warna']="MERAH") {
                        $takaranPh = ($getLahan->luas_lahan * ($getReferensiKapur->takaran+200))/10000;    
                    }
                    if ($getSensor['warna']="KUNING") {
                        $takaranPh = ($getLahan->luas_lahan * ($getReferensiKapur->takaran+400))/10000;    
                    }
                    $takaranKeasaman = [
                        'takaranPh' => $takaranPh,
                        'keterangan' => $keterangan,
                    ];
                }
            }

            //Pencarian Pupuk
            if ($getSensor['warna']) {
                $getReferensiPupuk = ReferensiPupuk::where('warna_tanah',$getSensor['warna'])->first();
                $sebelumTanam = ($getLahan->luas_lahan * $getReferensiPupuk->sebelum_tanam)/10000;
                $faseVegetative = ($getLahan->luas_lahan * $getReferensiPupuk->fase_vegetative)/10000;
                $npkGenerative = ($getLahan->luas_lahan * $getReferensiPupuk->fase_generative)/10000;
                $ureaGenerative = (4 * $npkGenerative)/3;

                $takaranPupuk = [
                    'sebelum_tanam' => $sebelumTanam,
                    'fase_vegetative' => $faseVegetative,
                    'npk_generative' => $npkGenerative,
                    'urea_generative' => $ureaGenerative
                ];
            }
            $HasilAkhir = HasilAkhir::where('lahan_id',$getLahanId)->update([
                'takaran_air' => json_encode($takaranAir),
                'takaran_keasaman' => json_encode($takaranKeasaman),
                'takaran_pupuk' => json_encode($takaranPupuk)
            ]);

            return redirect(route('hasil-akhir.index'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/hasil-akhir/create.blade.php
@extends('layouts.dashboard')

@section('styles')
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.css" />
@endsection

@section('content')

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      {!! Form::open([
          'url' => route('hasil-akhir.store'),
          'method' => 'POST',
          'enctype' => 'multipart/form-data'
          ])
      !!}
      {!! csrf_field() !!}
        @include('admin.hasil-akhir.form')
      {!! Form::close() !!}
    </div>
  </div>

@endsection
@section('scripts')
  <script src="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.min.js"></script>
  <script type="text/javascript">
    jQuery(document).ready(function() {
      jQuery('#description').summernote({
        height: 300,
      });
    });
  </script>
@endsection

resources/views/admin/hasil-akhir/edit.blade.php
@extends('layouts.dashboard')

@section('styles')
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.css" />
  {{-- <link rel="stylesheet" type="text/css" href="{{ asset('assets/admin-template/plugins/datatables/DataTables-1.10.18/css/dataTables.bootstrap.min.css') }}"> --}}

@endsection

@section('content')

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      {!! Form::model($data, ['url' => route('categories.update',$data->id), 'method' => 'PUT','enctype'=>'multipart/form-data']) !!}
      {!! csrf_field() !!}
        @include('admin.categories.form')
      {!! Form::close() !!}
    </div>
  </div>

@endsection

@section('scripts')
  <script src="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.min.js"></script>
  <script type="text/javascript">
    jQuery(document).ready(function() {
      jQuery('#description').summernote({
        height: 300,
      });
    });
  </script>
@endsection

resources/views/admin/hasil-akhir/form.blade.php
<div class="row">
	<div class="col-md-12">
	    <button type="submit" class="btn btn-primary btn-sm center">
	      <i class="fas fa-arrow-right"></i> lanjut
	    </button>
	    <div style="padding-bottom:20px;"></div>
	</div>

</div>

resources/views/admin/hasil-akhir/index.blade.php
@extends('layouts.dashboard')
@section('content')

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <p>
            <a href="{{ route('hasil-akhir.create') }}" class="btn btn-primary btn-sm">
                <i class="fa fa-plus">New</i>
            </a>    
        </p>
        
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12">

      <table id="hasil_akhir_datatable" class="table table-striped dt-responsive nowrap dataTable no-footer dtr-inline collapsed" style="width:100%;">

        <thead>
          <tr>
            <th class="text-center">No</th>
            <th class="text-center">Nama Pemilik</th>
            <th class="text-center">Takaran Air</th>
            <th class="text-center">Takaran Kapur</th>
            <th class="text-center">Takaran Pupuk</th>
            <th class="text-center">Action</th>
          </tr>
        </thead>

        <tbody>
          
          @php
            $no= 1;
          @endphp


          @foreach($data as $row)
          <tr class="text-center">
            <td class="text-center">{{$no}}</td>
            <td class="text-center">{{$row->lahan->keterangan}}</td>
            <td class="text-center">{{$row->takaran_air}}</td>
            <td class="text-center">{{$row->takaran_keasaman}}</td>
            <td class="text-center">{{$row->takaran_pupuk}}</td>
            <td class="text-center">
              <a href="{{ route('hasil-akhir.edit',$row->id) }}" class="btn btn-primary btn-sm">
                <i class="fa fa-edit"></i>
              </a>
                
              {!! Form::open(array(
                  'route'=>array('hasil-akhir.destroy',$row->id),
                  'method'=>'DELETE',
                  '_token'=> csrf_token(),
                  'style' => 'display:inline')) !!}
    
                  <button class="btn btn-danger btn-sm" type="submit"><i class="fa fa-trash"></i></button>
              {!!Form::close()!!}
                
            </td>
          </tr>

          @php
            $no++;
          @endphp

          @endforeach

        </tbody>  

      </table>
    </div>
  </div>

@endsection

@section('scripts') 

  <script type="text/javascript">
    jQuery('#hasil_akhir_datatable').DataTable();
  </script>

@endsection