routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.dashboard', [
    	'title' => "Dasboard"
    ]);
});
Route::resource('/nutrisi/lahan', 'Admin\LahanController');
Route::resource('/nutrisi/sensor', 'Admin\SensorController');
Route::resource('/nutrisi/hasil-akhir', 'Admin\HasilAkhirController');

app/Http/Controllers/Admin/SensorController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\HasilAkhir;
use App\lahan;

class SensorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['title'] = "Data Sensor";
        $data['data'] = HasilAkhir::with('lahan')->get();
        // return $data;
        return view('admin.sensor.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.sensor.create',['title' => "Masukkkan Nilai Sensor"]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $sessionLahanId = $request->session()->get('lahan_id');
        $getLahanId = HasilAkhir::where('lahan_id', $sessionLahanId)->first();
        if (!$getLahanId) {
            $deteksiSensor = HasilAkhir::create([
                'lahan_id' => $sessionLahanId,
                'sensor_kelembapan' =>$request->sensor_kelembapan,
                'sensor_keasaman' =>$request->sensor_keasaman,
                'sensor_warna' =>$request->sensor_warna,
            ]);
        }
        $deteksiSensor = HasilAkhir::where('lahan_id',$sessionLahanId)
        ->update([
            'sensor_kelembapan' =>$request->sensor_kelembapan,
            'sensor_keasaman' =>$request->sensor_keasaman,
            'sensor_warna' =>$request->sensor_warna,
        ]);

        return redirect(route('hasil-akhir.create'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/sensor/create.blade.php
@extends('layouts.dashboard')

@section('styles')
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.css" />
@endsection

@section('content')

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      {!! Form::open([
          'url' => route('sensor.store'),
          'method' => 'POST',
          'enctype' => 'multipart/form-data'
          ])
      !!}
      {!! csrf_field() !!}
        @include('admin.sensor.form')
      {!! Form::close() !!}
    </div>
  </div>

@endsection
@section('scripts')
  <script src="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.min.js"></script>
  <script type="text/javascript">
    jQuery(document).ready(function() {
      jQuery('#description').summernote({
        height: 300,
      });
    });
  </script>
@endsection

resources/views/admin/sensor/edit.blade.php
@extends('layouts.dashboard')

@section('styles')
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.css" />
  {{-- <link rel="stylesheet" type="text/css" href="{{ asset('assets/admin-template/plugins/datatables/DataTables-1.10.18/css/dataTables.bootstrap.min.css') }}"> --}}

@endsection

@section('content')

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      {!! Form::model($data, ['url' => route('categories.update',$data->id), 'method' => 'PUT','enctype'=>'multipart/form-data']) !!}
      {!! csrf_field() !!}
        @include('admin.categories.form')
      {!! Form::close() !!}
    </div>
  </div>

@endsection

@section('scripts')
  <script src="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.11/summernote.min.js"></script>
  <script type="text/javascript">
    jQuery(document).ready(function() {
      jQuery('#description').summernote({
        height: 300,
      });
    });
  </script>
@endsection

resources/views/admin/sensor/form.blade.php
<div class="row">

	<div class="col-md-12">
		<div class="form-group">
			<label class="col-md-2 control-label" for="sensor_keasaman">Sensor Keasaman</label>
			<div class="col-md-10">
				{{ Form::text('sensor_keasaman', null, ['class' => 'form-control','id' => 'sensor_keasaman','placeholder' => 'Sensor Keasaman']) }}
			</div>
		</div>
		<div style="padding-bottom:50px;"></div>
	</div>

	<div class="col-md-12">
		<div class="form-group">
			<label class="col-md-2 control-label" for="sensor_kelembapan">Sensor Kelembapan</label>
			<div class="col-md-10">
				{{ Form::select('sensor_kelembapan', ['KERING' => 'Kering', 'LEMBAB' => 'Lembab', 'BASAH' => 'Basah'], null, ['class' => 'form-control','id' => 'sensor_kelembapan','placeholder' => 'Sensor Kelembapan']) }}
			</div>
		</div>
		<div style="padding-bottom:50px;"></div>
	</div>

	<div class="col-md-12">
		<div class="form-group">
			<label class="col-md-2 control-label" for="sensor_warna">Sensor Warna</label>
			<div class="col-md-10">
				{{ Form::select('sensor_warna', ['KELABU' => 'Kelabu Hitam', 'MERAH' => 'Merah', 'KUNING' => 'Kuning'], null, ['class' => 'form-control','id' => 'sensor_warna','placeholder' => 'Sensor Warna']) }}
			</div>
		</div>
		<div style="padding-bottom:50px;"></div>
	</div>
	
	<div class="col-md-12">
	    <button type="submit" class="btn btn-primary btn-sm pull-right">
	      <i class="fa fa-save"></i> Simpan
	    </button>
	    <div style="padding-bottom:20px;"></div>
	</div>

</div>

resources/views/admin/sensor/index.blade.php
@extends('layouts.dashboard')
@section('content')

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <p>
            <a href="{{ route('sensor.create') }}" class="btn btn-primary btn-sm">
                <i class="fa fa-plus">New</i>
            </a>    
        </p>
        
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12">

      <table class="table lahan_datatable">

        <thead>
          <tr>
            <th class="text-center">No</th>
            <th class="text-center">Luas Lahan</th>
            <th class="text-center">Keterangan Pemilik</th>
            <th class="text-center">Sensor Keasaman</th>
            <th class="text-center">Sensor Kelembapan</th>
            <th class="text-center">Sensor Warna</th>
            <th class="text-center">Action</th>
          </tr>
        </thead>

        <tbody>
          @php
            $no= 1;
          @endphp


          @foreach($data as $row)
          <tr class="text-center">
            <td class="text-center">{{$no}}</td>
            <td class="text-center">{{$row->lahan->luas_lahan}}</td>
            <td class="text-center">{{$row->lahan->keterangan}}</td>
            <td class="text-center">{{$row->sensor_keasaman}}</td>
            <td class="text-center">{{$row->sensor_kelembapan}}</td>
            <td class="text-center">{{$row->sensor_warna}}</td>
            <td class="text-center">
              <a href="{{ route('sensor.edit',$row->id) }}" class="btn btn-primary btn-sm">
                <i class="fa fa-edit"></i>
              </a>
                
              {!! Form::open(array(
                  'route'=>array('sensor.destroy',$row->id),
                  'method'=>'DELETE',
                  '_token'=> csrf_token(),
                  'style' => 'display:inline')) !!}
    
                  <button class="btn btn-danger btn-sm" type="submit"><i class="fa fa-trash"></i></button>
              {!!Form::close()!!}
                
            </td>
          </tr>

          @php
            $no++;
          @endphp

          @endforeach

        </tbody>  

      </table>
    </div>
  </div>

@endsection

@section('scripts') 

  <script type="text/javascript">
    jQuery('.lahan_datatable').DataTable();
  </script>

@endsection