routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.dashboard', [
    	'title' => "Dasboard"
    ]);
});
Route::resource('/nutrisi/lahan', 'Admin\LahanController');
Route::resource('/nutrisi/sensor', 'Admin\SensorController');
Route::resource('/nutrisi/hasil-akhir', 'Admin\HasilAkhirController');

resources/views/includes/admin/css.blade.php
<link rel="stylesheet" type="text/css" href="{{ asset('assets/admin-template/themes/bootstrap/css/bootstrap.min.css') }}">

<link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/ionicons/4.4.1/collection/icon/icon.css" />
<link href="//cdn.materialdesignicons.com/1.1.34/css/materialdesignicons.min.css" rel="stylesheet" type="text/css">

<link rel="stylesheet" type="text/css" href="{{ asset('assets/admin-template/themes/webadmin/css/style.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('assets/admin-template/plugins/DataTables/DataTables-1.10.18/css/dataTables.bootstrap.min.css') }}">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.min.css">

resources/views/includes/admin/js.blade.php
{{-- <script src="/assets/plugins/jquery/jquery-1.11.min.js"></script> --}}
<script src="{{ asset('assets/admin-template/plugins/jquery/jquery-2.2.0.min.js') }}"></script>
<script src="{{ asset('assets/admin-template/themes/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/admin-template/plugins/modernizer/modernizer.min.js') }}"></script>
<script src="{{ asset('assets/admin-template/plugins/jquery/detect.js') }}"></script>
<script src="{{ asset('assets/admin-template/plugins/fastclick/fastclick.js') }}"></script>
<script src="{{ asset('assets/admin-template/plugins/jquery/jquery.slimscroll.js') }}"></script>
<script src="{{ asset('assets/admin-template/plugins/jquery/jquery-blockui/jquery.blockui.js') }}"></script>
<script src="{{ asset('assets/admin-template/plugins/waves/waves.js') }}"></script>
<script src="{{ asset('assets/admin-template/plugins/wow/wow.min.js') }}"></script>
<script src="{{ asset('assets/admin-template/plugins/jquery/jquery.nicescroll.js') }}"></script>
<script src="{{ asset('assets/admin-template/plugins/jquery/jquery.scrollTo.min.js') }}"></script>
<script src="{{ asset('assets/admin-template/themes/webadmin/js/webadmin.js') }}"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
{{-- <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script> --}}
{{-- <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script> --}}
<script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jQuery-slimScroll/1.3.8/jquery.slimscroll.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jQuery-slimScroll/1.3.8/jquery.slimscroll.js"></script>

resources/views/includes/admin/meta.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="csrf-token" content="{{ csrf_token() }}">

resources/views/includes/admin/side-menu.blade.php
@php
  $colorArray = ['00cec9','2d3436','d63031','fdcb6e','6c5ce7'];
@endphp
<div class="left side-menu">
  <div class="sidebar-inner slimscrollleft">
    <div class="user-details">
      <div class="text-center">
        <img src="https://ui-avatars.com/api/?background={{ $colorArray[rand(0,4)] }}&color=fff&name=zezen" alt="" class="img-circle">
      </div>
      <div class="user-info">
        <div class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            zezen
          </a>
        </div>
      </div>
    </div>
    <div id="sidebar-menu">
      <ul>
        <li>
          <a href="javascript:void(0)">
            <i class="mdi mdi-home"></i>
            <span>
              Beranda
            </span>
          </a>
        </li>
      {{-- Menu Data Master --}}
        <li class="has_sub">
          <a href="javascript:void(0)">
            <i class="mdi mdi-database"></i>
            <span>
              Data Nutrisi
            </span>
            
            <span class="pull-right">
              <i class="mdi mdi-plus"></i>
            </span>
          </a>

          <ul class="list-unstyled">
            <li>
              <a href="{{ route('lahan.index') }}">
                Data Lahan
              </a>
            </li>
            <li>
              <a href="{{ route('sensor.index') }}">
                Data Sensor
              </a>
            </li>
            <li>
              <a href="{{ route('hasil-akhir.index') }}">
                Data Akhir
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  <div class="clearfix"></div>
  </div>
</div>

resources/views/includes/admin/topbar.blade.php
@php
  $colorArray = ['00cec9','2d3436','d63031','fdcb6e','6c5ce7'];
@endphp
<div class="topbar">
    <div class="topbar-left">
        <div class="text-center">
            <a href="" class="logo"><span>Web</span>Admin</a>
            <a href="javascript:void(0)" class="logo-sm"><span>W</span></a>
        </div>
    </div>
    <div class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="">
                <div class="pull-left">
                    <button type="button" class="button-menu-mobile open-left waves-effect waves-light">
                        <i class="mdi mdi-menu"></i>
                    </button>
                    <span class="clearfix"></span>
                </div>

                <ul class="nav navbar-nav navbar-right pull-right">
                    <li class="hidden-xs">
                        <a href="javascript:void(0)" id="btn-fullscreen" class="waves-effect waves-light notification-icon-box">
                            <i class="mdi mdi-fullscreen"></i>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="" class="dropdown-toggle profile waves-effect waves-light" data-toggle="dropdown" aria-expanded="true">
                            <img src="https://ui-avatars.com/api/?background={{ $colorArray[rand(0,4)] }}&color=fff&name=zezen" alt="" class="img-circle">
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="javascript:void(0)">
                                    Profil
                                </a>
                            </li>
                            <li>
                                <a href="javascript:void(0)">
                                    Pengaturan
                                </a>
                            </li>
                            
                            <li class="divider"></li>
                            <li>
                                <a href="{{ url('/') }}">
                                    Keluar
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>